<a href="https://colab.research.google.com/github/icaanisa25/MSIB/blob/main/Salinan_dari_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

# Creating Arrays

In [ ]:
# Import Library NumPy
import numpy as np

# Contoh Membuat Array
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

In [ ]:
# Menampilkan Array a
a

array([1, 2, 3])

In [ ]:
# Menampilkan Array b
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
# Menampilkan Array c
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [ ]:
# Create an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Create an array of ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
# Create an array of evenly spaced values (step value)
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [ ]:
# Create an array of evenly spaced values (number of samples)
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Create a constant array
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [ ]:
# Create a 2X2 identity matrix
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Create an array with random values
np.random.random((2,2))

array([[0.96131572, 0.22307389],
       [0.91852946, 0.83996858]])

In [ ]:
# Create an empty array
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# Input Output

### Saving & Loading On Disk

In [ ]:
# np.save('my_array', a)
# np.savez('array.npz', a, b)
# np.load('my_array.npy')

In [ ]:
# np.loadtxt("myfile.txt")
# np.genfromtxt("my_file.csv", delimiter=',')
# np.savetxt("myarray.txt", a, delimiter=" ")

# Data Types

In [ ]:
# Signed 64-bit integer types
np.int64

numpy.int64

In [ ]:
# Standard double-precision floating point
np.float32

numpy.float32

In [ ]:
# Complex numbers represented by 128 floats
np.complex

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


complex

In [ ]:
# Boolean type storing TRUE and FALSE values
np.bool

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


bool

In [ ]:
# Python object type
np.object

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


object

In [ ]:
# Fixed-length string type
np.string_

numpy.bytes_

In [ ]:
# Fixed-length unicode type
np.unicode_

numpy.str_

# Inspecting Your Array 

In [ ]:
# Array dimensions
a.shape

(3,)

In [ ]:
# Length of array
len(a)

3

In [ ]:
# Number of array dimensions
b.ndim

2

In [ ]:
# Number of array elements
e.size

4

In [ ]:
# Data type of array elements
b.dtype

dtype('float64')

In [ ]:
# Name of data type
b.dtype.name

'float64'

In [ ]:
# Convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Array Mathematics
## Arithmetic Operations

### Subtraction

In [ ]:
# Pengurangan Array - a-b
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
# Pengurangan Array - a-b
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

### Addition

In [ ]:
# Penjumlahan Array - b+a
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
# Penjumlahan Array - b+a
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

### Division

In [ ]:
# Pembagian Array - a/b
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
# Pembagian Array - a/b
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

### Multiplication

In [ ]:
# Perkalian Array - a*b
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
# Perkalian Array - a*b
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

### Exponentiation

In [ ]:
# Fungsi eksponensial pada array b
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

### Square root

In [ ]:
# Fungsi akar pada array b
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Print sines of an array

In [ ]:
# Nilai Sinus pada array a
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

### Element-wise cosine 

In [ ]:
# Nilai Cosinus pada array b
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

### Element-wise natural logarithm

In [ ]:
# Nilai logaritma pada array a
np.log(a)

array([0.        , 0.69314718, 1.09861229])

### Dot product

In [ ]:
# Perkalian Titik pada array f
e.dot(f)

array([[7., 7.],
       [7., 7.]])

## Comparison

### Element-wise comparison

In [ ]:
# Perbandingan elemen array a==b 
a == b

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
# Perbandingan elemen array a<2
a < 2

array([ True, False, False])

### Array-wise comparison

In [ ]:
# Perbandingan array a,b
np.array_equal(a, b)

False

## Aggregate Functions

### Array-wise sum

In [ ]:
# Agregasi nilai total array a
a.sum()

6

### Array-wise minimum value

In [ ]:
# Agregasi nilai minimal array a
a.min()

1

### Maximum value of an array row

In [ ]:
# Agregasi nilai maksimal array b
b.max(axis=0)

array([4., 5., 6.])

### Cumulative sum of the elements

In [ ]:
# Nilai kumulatif pada array b
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

### Mean

In [ ]:
# Nilai Mean array a
a.mean()

2.0

### Median 

In [ ]:
# Nilai Median array b
np.median(b)

3.5

### Correlation coefficient

In [ ]:
# Nilai korelasi koefisien array a
np.corrcoef(a)

1.0

### Standard deviation

In [ ]:
# Nilai standar defiasi array b
np.std(b)

1.5920810978785667

# Copying Arrays

### Create a view of the array with the same data

In [ ]:
# Melihat isi array a
h = a.view()
h

array([1, 2, 3])

### Create a copy of the array

In [ ]:
# Copy array a
np.copy(a)

array([1, 2, 3])

### Create a deep copy of the array

In [ ]:
# Deef copy array a
h = a.copy()
h

array([1, 2, 3])

# Sorting Arrays

### Sort an array

In [ ]:
# Mengurutkan array a
a.sort()
a

array([1, 2, 3])

### Sort the elements of an array's axis

In [ ]:
# Mengurutkan array c
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

# Subsetting, Slicing, Indexing

## Subsetting

### Select the element at the 2nd index

In [ ]:
# Mengambil nilai index ke 2 pada elemen array a
a[2]

3

### Select the element at row 1 column 2 (equivalent to b[1][2])


In [ ]:
# Mengambil nilai baris ke 1 kolom ke 2 pada elemen array a
b[1,2]

6.0

## Slicing

### Select items at index 0 and 1

In [ ]:
# Mengambil nilai index ke 0 - 1 pada elemen array a
a[0:2]

array([1, 2])

### Select items at rows 0 and 1 in column 1

In [ ]:
# Mengambil nilai index ke 0 - 1 kolom ke 1 pada elemen array b
b[0:2,1] 

array([2., 5.])

### Select all items at row 0 (equivalent to b[0:1, :])

In [ ]:
# Mengambil semua nilai baris ke 0 pada elemen array b
b[:1]

array([[1.5, 2. , 3. ]])

### Same as [1,:,:]

In [ ]:
# Mengambil semua nilai baris ke 1 pada elemen array c
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

### Reversed array a 

In [ ]:
# Mengambil nilai pada elemen array a secara terbalik
a[ : :-1]

array([3, 2, 1])

# Array Manipulation

## Transposing Array

### Permute array dimensions

In [ ]:
# Transpose array b
i = np.transpose(b)

In [ ]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

##  Changing Array Shape

### Flatten the array

In [ ]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
# Meratakan array b menjadi satu dimensi
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

### Reshape, but don’t change data

In [ ]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
# Mengubah array g menjadi 2 dimensi
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## Adding/Removing Elements

### Return a new array with shape (2,6) 

In [ ]:
h

array([1, 2, 3])

In [ ]:
# Menambah jumlah elemen array
np.resize(h, (2,6))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

### Append items to an array

In [ ]:
h

array([1, 2, 3])

In [ ]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
# Menambahkan elemen array h dengan array g 
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

### Insert items in an array

In [ ]:
a

array([1, 2, 3])

In [ ]:
# Memasukkan nilai 5 index ke 1 dalam array a
np.insert(a, 1, 5)

array([1, 5, 2, 3])

### Delete items from an array

In [ ]:
a

array([1, 2, 3])

In [ ]:
# Menghapus elemen array a index ke 1
np.delete(a,[1])

array([1, 3])

## Combining Arrays

###  Concatenate arrays

In [ ]:
a

array([1, 2, 3])

In [ ]:
d

array([10, 15, 20])

In [ ]:
# Menggabungkan elemen array a dan d
np.concatenate((a,d),axis=0) 

array([ 1,  2,  3, 10, 15, 20])

### Stack arrays vertically (row-wise)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
# Susunan array secara vertikal (berdasarkan baris) array a dan b
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Stack arrays vertically (row-wise)

In [ ]:
e

array([[7, 7],
       [7, 7]])

In [ ]:
f

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Susunan array secara vertikal (berdasarkan baris) array e dan f
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

### Stack arrays horizontally (column-wise)

In [ ]:
# Susunan array secara horizontal (berdasarkan kolom) array e dan f
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

### Create stacked column-wise arrays 

In [ ]:
a

array([1, 2, 3])

In [ ]:
d

array([10, 15, 20])

In [ ]:
# Susunan berdasarkan kolom array a dan d
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### Create stacked column-wise arrays

In [ ]:
# Susunan berdasarkan kolom array a dan d
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## Splitting Arrays

### Split the array horizontally at the 3rd index

In [ ]:
# Memisahkan array a secara horizontal pada indeks ke-3
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

### Split the array vertically at the 2nd index

In [ ]:
# Memisahkan array c secara vertikal pada indeks ke-2
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]

# Thank You